import type { Metadata } from "next";
import { Amplify } from "aws-amplify";
import config from "../amplifyconfiguration.json";
import AuthenticationProvider from "@/providers/authentication";
import MantineThemeProvider from "@/providers/mantine";
import MainLayout from "@/components/mainLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

Amplify.configure(config, { ssr: true });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineThemeProvider>
          <AuthenticationProvider>
            <MainLayout>{children}</MainLayout>
          </AuthenticationProvider>
        </MantineThemeProvider>
      </body>
    </html>
  );
}
