import type { Metadata } from "next";
import { Amplify } from "aws-amplify";
import config from "../amplifyconfiguration.json";
import AuthenticationProvider from "@/providers/authentication";
import { MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
import { myTheme } from "@/styles/mantineTheme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

Amplify.configure(config, { ssr: true });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={myTheme}>
          <AuthenticationProvider>{children}</AuthenticationProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
